# Generated by Django 3.2.12 on 2022-06-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulapricerecord',
            name='size',
        ),
        migrations.AddField(
            model_name='formulapricerecord',
            name='footboard_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulapricerecord',
            name='inset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
