# Generated by Django 3.2.12 on 2022-06-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_records", "0008_alter_formulapricelistpricerecord_rule_display_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulapricelistpricerecord",
            name="rule_display_2",
        ),
        migrations.AlterField(
            model_name="formulapricelistpricerecord",
            name="rule_display_1",
            field=models.CharField(
                blank=True,
                default=" ",
                help_text="ex. 67 x 19 x 29 H",
                max_length=200,
                null=True,
            ),
        ),
    ]
