# Generated by Django 3.2.12 on 2022-07-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_records', '0011_auto_20220705_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulapricerecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pricelistpricerecord',
            options={'ordering': ['order']},
        ),
    ]
