# Generated by Django 3.2.12 on 2022-07-06 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("price_records", "0012_auto_20220705_1324"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricerecord",
            options={"ordering": ["order", "rule_display_1"]},
        ),
    ]
