# Generated by Django 3.2.12 on 2022-07-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("price_records", "0016_pricerecord_is_surcharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelistpricerecord",
            name="is_surcharge",
            field=models.BooleanField(default=False),
        ),
    ]
