# Generated by Django 3.2.12 on 2022-11-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_records', '0022_formulapricerecord_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulapricerecord',
            options={'ordering': ['order']},
        ),
    ]
