# Generated by Django 3.2.12 on 2023-05-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("price_records", "0027_alter_pricerecord_man_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulapricerecord",
            name="rule_display_1",
            field=models.CharField(
                default="",
                help_text="Will convert [attribute] L x [attribute] D or you can just manually ",
                max_length=200,
            ),
        ),
    ]
