# Generated by Django 3.2.12 on 2023-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_records', '0028_alter_formulapricerecord_rule_display_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulapricerecord',
            name='rule_display_1',
            field=models.CharField(default='', help_text='Will convert [attribute] L x [attribute] D ', max_length=200),
        ),
    ]
