# Generated by Django 3.2.12 on 2023-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_records', '0029_alter_formulapricerecord_rule_display_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulapricerecord',
            name='gbp_price',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formulapricerecord',
            name='gbp_price_no_vat',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formulapricerecord',
            name='gbp_trade',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formulapricerecord',
            name='gbp_trade_no_vat',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
