# Generated by Django 3.2.12 on 2022-06-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formula_tear_sheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulatearsheet",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
