# Generated by Django 3.2.12 on 2022-07-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_tear_sheets", "0003_formulatearsheet_footer_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulatearsheet",
            name="template",
            field=models.CharField(
                choices=[
                    ("A", "ONE COLUMN DISPLAY"),
                    ("B", "TWO COLUMN DISPLAY"),
                    ("C", "RULE TYPE ABOVE"),
                ],
                default="B",
                max_length=1000,
            ),
        ),
    ]
