# Generated by Django 3.2.12 on 2023-05-10 17:04

from django.db import migrations, models
import formula_tear_sheets.models


class Migration(migrations.Migration):
    dependencies = [
        ("formula_tear_sheets", "0005_formulatearsheet_sdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulatearsheet",
            name="gbp_sdata",
            field=models.JSONField(
                blank=True,
                default=formula_tear_sheets.models.gbp_sdata_json_default,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formulatearsheet",
            name="gbp_template",
            field=models.CharField(
                choices=[
                    ("A", "ONE COLUMN DISPLAY"),
                    ("B", "TWO COLUMN DISPLAY"),
                    ("C", "RULE TYPE ABOVE"),
                ],
                default="C",
                max_length=1000,
            ),
        ),
    ]
