# Generated by Django 3.2.12 on 2022-07-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tear_sheets", "0002_tearsheet_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="tearsheet",
            name="footer_space",
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
    ]
