# Generated by Django 3.2.12 on 2022-07-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tear_sheets", "0004_tearsheet_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tearsheet",
            name="template",
            field=models.CharField(
                choices=[("A", "Template A"), ("B", "Template B"), ("C", "Template C")],
                default="B",
                max_length=1000,
            ),
        ),
    ]
