# Generated by Django 3.2.12 on 2023-05-02 20:14

from django.db import migrations, models
import tear_sheets.models


class Migration(migrations.Migration):
    dependencies = [
        ("tear_sheets", "0007_tearsheet_sdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="tearsheet",
            name="gbp_sdata",
            field=models.JSONField(
                blank=True,
                default=tear_sheets.models.TearSheet.gbp_sdata_json_default,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tearsheet",
            name="sdata",
            field=models.JSONField(
                blank=True,
                default=tear_sheets.models.TearSheet.sdata_json_default,
                null=True,
            ),
        ),
    ]
