name: CI

# Enable Buildkit and let compose use it to speed up image building
# testing
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['staging']
    paths-ignore: ['docs/**']

  push:
    branches: ['staging']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BDDW_PRICES_STAGING_HOST }}
        username: ${{ secrets.BDDW_EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/django-projects/bddw_prices/
          chmod +x deploy-staging.sh
          ./deploy-staging.sh

  # # With no caching at all the entire ci process takes 4m 30s to complete!
  # pytest:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout Code Repository
  #       uses: actions/checkout@v4
  #
  #     - name: Build the Stack
  #       run: docker compose -f local.yml build
  #
  #     - name: Run DB Migrations
  #       run: docker compose -f local.yml run --rm django python manage.py migrate
  #
  #     - name: Run Django Tests
  #       run: docker compose -f local.yml run django pytest
  #
  #     - name: Tear down the Stack
  #       run: docker compose -f local.yml down
