# Generated by Django 3.2.12 on 2022-06-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tear_sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(blank=True, help_text='The order number when this Category appears with other Categories.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(blank=True, help_text='The order number when this Item appears with other Items.', null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(blank=True, help_text='The order number when this series appears with other Series.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CatSeriesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, help_text='The order number when this Category Series Item appears with other Category Series Items.', null=True)),
                ('formula', models.CharField(blank=True, default=None, help_text='The string version of the formula', max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.series')),
                ('tear_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tear_sheets.tearsheet')),
            ],
            options={
                'verbose_name': 'Category Series Item',
                'verbose_name_plural': 'Category Series Items',
                'ordering': ['order'],
            },
        ),
    ]
