# Generated by Django 3.2.12 on 2022-06-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tear_sheets", "0001_initial"),
        ("products", "0002_auto_20220608_0845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catseriesitem",
            name="tear_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tear_sheets.tearsheet",
            ),
        ),
    ]
