# Generated by Django 3.2.12 on 2022-06-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220613_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catseriesitem',
            options={'ordering': ['category'], 'verbose_name': 'Category Series Item', 'verbose_name_plural': 'Category Series Items'},
        ),
    ]
