# Generated by Django 3.2.12 on 2022-06-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220629_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catseriesitem',
            options={'ordering': ['cat_order', 'series_order', 'item_order'], 'verbose_name': 'Category Series Item', 'verbose_name_plural': 'Category Series Items'},
        ),
        migrations.AddField(
            model_name='catseriesitem',
            name='cat_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catseriesitem',
            name='item_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catseriesitem',
            name='series_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
