# Generated by Django 3.2.12 on 2022-07-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_auto_20220629_0834"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order"], "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
