# Generated by Django 3.2.12 on 2022-07-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_auto_20220705_0824"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="pricelist_ignore",
            field=models.BooleanField(default=False),
        ),
    ]
