# Generated by Django 3.2.12 on 2026-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_catseriesitem_opt_series_item_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tearsheet_grouping',
            field=models.CharField(choices=[('by_item', 'By Item (one tearsheet per Category-Series-Item)'), ('by_series', 'By Series (one tearsheet per Category-Series)')], default='by_item', help_text='Controls whether tearsheets are grouped by individual items or by the entire series', max_length=20),
        ),
    ]
